### ISSUE TITLE
ontap select upgrade node image selection

### ISSUE THREAD

**Issue by nicoxnoise** [NetAppDocs/ontap-select#146]
Page: [Upgrading the ONTAP Select nodes](https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html)
Hello,

**The documentation explain following :**
"After you deploy an ONTAP Select cluster, you can upgrade the ONTAP image of each node as needed using the standard ONTAP software upgrade procedure."

When we reach the Netapp support downloading page, there are now 2  downloading link :

- ONTAP Select Node Upgrade
- ONTAP 9

The two links doesn't reach to the same upgrade image name but the files seems to be identical (just 16Ko of differences between the 2 images for the last release 9.10.1RC1).

The **ONTAP 9** link reach to the **9101RC1_q_image.tgz image.** (2.40GB)
The **ONTAP Select Node Upgrade** link reach to the **ONTAPSELECT_9101RC1_UPGRADE.tgz** (2.40GB)

As mention before, if we use the "standard ONTAP software upgrade procedure", the user download the ONTAP image using the link **"ONTAP 9"**.
But now, the link **"ONTAP Select Node Upgrade"** lead into error.
Which link to use for ONTAP Select upgrade node ?

**Comment by dmp-netapp** [comment]
Thanks for your question. I am reviewing now.

**Comment by dmp-netapp** [comment]
You should use the link for *ONTAP Select Node Update* at the NetApp Support Site. I have updated the page you mention above and the documentation site has been refreshed. If you encounter some type of error with the upgrade procedure, please open an issue with support. You can also create another doc issue at this site, but I would need to refer it to someone else because I only maintain the doc.

**Comment by nicoxnoise** [comment]
Hello !
Thanks for your reactivity with the update of the documentation.
I think the ONTAP SELECT update node is New ans the documentation needed to
be updated.

Thanks a lot !

Le ven. 19 nov. 2021 à 19:22, David Peterson ***@***.***> a
écrit :
