### ISSUE TITLE
when mentioning VSAN configuration, please add: ForceProvisioning recommendation

### ISSUE THREAD

**Issue by vgeert** [NetAppDocs/ontap-select#206]
### Page URL

https://docs.netapp.com/us-en/ontap-select/concept_stor_vsan_external.html

### Page title

VSAN and external array configurations

### Summary

When mentioning VSAN configuration, please add: ForceProvisioning recommendation

https://kb.netapp.com/onprem/ontap/ONTAP_Select/Deploy_OTS_on_VMware_vSAN_fails_with_error_%22File_system_specific_implementation_of_Ioctl_file_failed%22

This is almost never set and always needed for OTS

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. There will be no documentation update for this issue due to the [KB article](https://kb.netapp.com/onprem/ontap/ONTAP_Select/Deploy_OTS_on_VMware_vSAN_fails_with_error_%22File_system_specific_implementation_of_Ioctl_file_failed%22) content being sufficient. Let us know if you have any further questions - thanks!
